"""Readable snapshots for the supported public import surface."""

from importlib import import_module

PUBLIC_EXPORTS = {
    "runtime_contract": (
        "CandidateKind",
        "DiscoveryError",
        "DiscoveryErrorCode",
        "DiscoveryItem",
        "DiscoveryResult",
        "DiscoveryStats",
        "FileIdentity",
        "discover",
    ),
    "runtime_contract.analysis": (
        "AnalysisCompleteness",
        "AnalysisDiagnostic",
        "AnalysisResult",
        "AnalysisResultSchemaId",
        "Analyzer",
        "AnalyzerExecutionError",
        "AnalyzerInput",
        "AnalyzerNotRegisteredError",
        "AnalyzerRegistry",
        "AnalyzerRegistryError",
        "CandidateKindConflictError",
        "ClassificationResolver",
        "ComposeAnalyzer",
        "Confidence",
        "ConfigPolicyClassificationResolver",
        "DecisionSource",
        "DiagnosticCode",
        "DiagnosticParameter",
        "DockerfileAnalyzer",
        "DotenvAnalyzer",
        "DuplicateAnalyzerIdError",
        "EffectiveClassification",
        "FactKind",
        "FactObservation",
        "InvalidAnalyzerCallableError",
        "InvalidAnalyzerIdError",
        "InvalidSupportedKindsError",
        "JavaScriptTypeScriptAnalyzer",
        "KubernetesAnalyzer",
        "KubernetesProjectAnalysis",
        "PythonAstAnalyzer",
    ),
    "runtime_contract.compose": (
        "MAX_ACTIVE_PROFILES",
        "MAX_ALIAS_MERGE_REFERENCES",
        "MAX_BINDING_NAME_BYTES",
        "MAX_BUILD_ARG_ENTRIES",
        "MAX_COMPOSE_BYTES",
        "MAX_COMPOSE_SERVICES",
        "MAX_ENVIRONMENT_ENTRIES",
        "MAX_ENV_FILE_ENTRIES",
        "MAX_ENV_FILE_PATH_BYTES",
        "MAX_INTERPOLATIONS",
        "MAX_NAME_BYTES",
        "MAX_PROFILES_PER_SERVICE",
        "MAX_PROJECT_BYTES",
        "MAX_PROJECT_FILES",
        "MAX_PROJECT_REFERENCES",
        "MAX_PROVENANCE_STEPS",
        "MAX_REFERENCE_DEPTH",
        "MAX_SCALAR_BYTES",
        "MAX_SHELL_VARIABLE_NAMES",
        "MAX_YAML_DEPTH",
        "MAX_YAML_NODES",
        "ComposeBinding",
        "ComposeBindingKind",
        "ComposeDiagnostic",
        "ComposeDiagnosticCode",
        "ComposeEnvFile",
        "ComposeInput",
        "ComposeInterpolation",
        "ComposeInterpolationOperator",
        "ComposeInterpolationResolution",
        "ComposeLoadResult",
        "ComposeLoadStatus",
        "ComposeProjectInput",
        "ComposeProjectResult",
        "ComposeProvenanceOperation",
        "ComposeProvenanceOutcome",
        "ComposeProvenanceStep",
        "ComposeResolutionTrace",
        "ComposeService",
        "ComposeServiceActivation",
        "ComposeSourceKind",
        "ComposeUsedSource",
        "ComposeVariableSourceInput",
        "ComposeVariableSourceKind",
        "load_compose",
        "resolve_compose_project",
    ),
    "runtime_contract.kubernetes": (
        "MAX_ENV_ENTRIES",
        "MAX_ENV_FROM_ENTRIES",
        "MAX_KUBERNETES_BYTES",
        "MAX_KUBERNETES_OBJECTS",
        "MAX_KUBERNETES_OBJECT_KEYS",
        "MAX_YAML_ALIASES",
        "MAX_YAML_DEPTH",
        "MAX_YAML_DOCUMENTS",
        "MAX_YAML_NODES",
        "KubernetesContainerContext",
        "KubernetesContainerKind",
        "KubernetesDiagnostic",
        "KubernetesDiagnosticCode",
        "KubernetesEnvBinding",
        "KubernetesEnvFromSource",
        "KubernetesEnvFromSourceKind",
        "KubernetesEnvSourceKind",
        "KubernetesInput",
        "KubernetesLoadStatus",
        "KubernetesObjectKeyField",
        "KubernetesObjectKeyPresence",
        "KubernetesObjectKind",
        "KubernetesObjectPresence",
        "KubernetesReferenceKind",
        "KubernetesReferenceResolution",
        "KubernetesSourceStatus",
        "KubernetesTraversalResult",
        "KubernetesWorkloadKind",
        "traverse_kubernetes_workloads",
    ),
    "runtime_contract.domain": (
        "ConfigKey",
        "Consumer",
        "ConsumerAccessKind",
        "Contract",
        "ContractSchemaId",
        "Environment",
        "EnvironmentKind",
        "EvidenceKind",
        "Finding",
        "FindingParameter",
        "Phase",
        "Profile",
        "Provider",
        "ProviderMechanism",
        "ProviderRole",
        "RequirementSource",
        "RuleId",
        "SafeIdentifier",
        "SecretSource",
        "Severity",
        "SourceLocation",
    ),
    "runtime_contract.flow": (
        "FlowEdge",
        "FlowEdgeKind",
        "FlowGraph",
        "FlowNode",
        "FlowNodeKind",
        "FlowTrace",
        "build_flow_graph",
    ),
    "runtime_contract.normalization": (
        "NormalizationError",
        "NormalizationErrorCode",
        "normalize_observations",
    ),
    "runtime_contract.scan": (
        "ReportInputs",
        "ReportMetadata",
        "ScanFile",
        "ScanRequest",
        "ScanResult",
        "ScanRun",
        "ScanStatus",
        "ScanSummary",
        "parse_json_report",
        "render",
        "run_scan",
        "schema_bytes",
        "write_atomic",
    ),
}


def test_public_exports_match_reviewable_snapshot() -> None:
    for module_name, expected in PUBLIC_EXPORTS.items():
        module = import_module(module_name)
        assert tuple(module.__all__) == expected
        assert all(getattr(module, name) is not None for name in expected)


def test_documented_import_paths_are_supported() -> None:
    from runtime_contract.analysis import (
        AnalysisResult,
        AnalyzerInput,
        AnalyzerRegistry,
        KubernetesAnalyzer,
    )
    from runtime_contract.compose import ComposeInput, ComposeLoadResult, load_compose
    from runtime_contract.discovery import CandidateKind
    from runtime_contract.domain import (
        ConfigKey,
        Consumer,
        Contract,
        Environment,
        Finding,
        Provider,
        SourceLocation,
    )
    from runtime_contract.flow import FlowGraph, build_flow_graph
    from runtime_contract.kubernetes import (
        KubernetesInput,
        KubernetesTraversalResult,
        traverse_kubernetes_workloads,
    )
    from runtime_contract.normalization import normalize_observations
    from runtime_contract.scan import ScanResult, parse_json_report, render, run_scan, write_atomic

    assert all(
        item is not None
        for item in (
            AnalysisResult,
            AnalyzerInput,
            AnalyzerRegistry,
            KubernetesAnalyzer,
            CandidateKind,
            ComposeInput,
            ComposeLoadResult,
            ConfigKey,
            Consumer,
            Contract,
            Environment,
            Finding,
            FlowGraph,
            Provider,
            SourceLocation,
            normalize_observations,
            ScanResult,
            parse_json_report,
            render,
            run_scan,
            write_atomic,
            load_compose,
            KubernetesInput,
            KubernetesTraversalResult,
            traverse_kubernetes_workloads,
            build_flow_graph,
        )
    )
