"""Public static Docker Compose loading API."""

from runtime_contract.compose.loader import (
    MAX_ALIAS_MERGE_REFERENCES,
    MAX_BINDING_NAME_BYTES,
    MAX_BUILD_ARG_ENTRIES,
    MAX_COMPOSE_BYTES,
    MAX_COMPOSE_SERVICES,
    MAX_ENV_FILE_ENTRIES,
    MAX_ENV_FILE_PATH_BYTES,
    MAX_ENVIRONMENT_ENTRIES,
    MAX_INTERPOLATIONS,
    MAX_PROFILES_PER_SERVICE,
    MAX_SCALAR_BYTES,
    MAX_YAML_DEPTH,
    MAX_YAML_NODES,
    load_compose,
)
from runtime_contract.compose.models import (
    ComposeBinding,
    ComposeBindingKind,
    ComposeDiagnostic,
    ComposeDiagnosticCode,
    ComposeEnvFile,
    ComposeInput,
    ComposeInterpolation,
    ComposeInterpolationOperator,
    ComposeLoadResult,
    ComposeLoadStatus,
    ComposeService,
)

__all__ = [
    "MAX_ALIAS_MERGE_REFERENCES",
    "MAX_BINDING_NAME_BYTES",
    "MAX_BUILD_ARG_ENTRIES",
    "MAX_COMPOSE_BYTES",
    "MAX_COMPOSE_SERVICES",
    "MAX_ENVIRONMENT_ENTRIES",
    "MAX_ENV_FILE_ENTRIES",
    "MAX_ENV_FILE_PATH_BYTES",
    "MAX_INTERPOLATIONS",
    "MAX_PROFILES_PER_SERVICE",
    "MAX_SCALAR_BYTES",
    "MAX_YAML_DEPTH",
    "MAX_YAML_NODES",
    "ComposeBinding",
    "ComposeBindingKind",
    "ComposeDiagnostic",
    "ComposeDiagnosticCode",
    "ComposeEnvFile",
    "ComposeInput",
    "ComposeInterpolation",
    "ComposeInterpolationOperator",
    "ComposeLoadResult",
    "ComposeLoadStatus",
    "ComposeService",
    "load_compose",
]
